# Practical No. 9: End-to-End ETL Pipeline for E-Commerce Data

In [ ]:
import pandas as pd
import sqlite3
import os

print("Libraries imported successfully!")

Libraries imported successfully!

# STEP 1 — Create E-commerce CSV Files

STEP 1.1 — Create Customers CSV

In [ ]:
customers_data = {
    "Customer_ID": [1, 2, 3, 4, 5],
    "Name": ["Rahul", "Sneha", "Amit", "Priya", "Neha"],
    "City": ["Mumbai", "Pune", "Nashik", "Mumbai", "Thane"]
}

customers_df = pd.DataFrame(customers_data)

customers_df.to_csv(
    "customers.csv",
    index=False
)

print("customers.csv created successfully!")

customers.csv created successfully!

STEP 1.2 — Create Products CSV

In [ ]:
products_data = {
    "Product_ID": [101, 102, 103, 104, 105],
    "Product": [
        "Laptop",
        "Mouse",
        "Chair",
        "Mobile",
        "Keyboard"
    ],
    "Category": [
        "Electronics",
        "Electronics",
        "Furniture",
        "Electronics",
        "Electronics"
    ],
    "Price": [
        50000,
        2000,
        8000,
        30000,
        3000
    ]
}

products_df = pd.DataFrame(products_data)

products_df.to_csv(
    "products.csv",
    index=False
)

print("products.csv created successfully!")

products.csv created successfully!

STEP 1.3 — Create Orders CSV

In [ ]:
orders_data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005],
    "Customer_ID": [1, 2, 3, 4, 5],
    "Product_ID": [101, 102, 103, 104, 105],
    "Quantity": [1, 3, 2, 1, 2]
}

orders_df = pd.DataFrame(orders_data)

orders_df.to_csv(
    "orders.csv",
    index=False
)

print("orders.csv created successfully!")

orders.csv created successfully!

STEP 2.4 — Create Payments CSV

In [ ]:
payments_data = {
    "Payment_ID": [501, 502, 503, 504, 505],
    "Order_ID": [1001, 1002, 1003, 1004, 1005],
    "Amount": [50000, 6000, 16000, 30000, 6000],
    "Status": [
        "Paid",
        "Paid",
        "Paid",
        "Pending",
        "Paid"
    ]
}

payments_df = pd.DataFrame(payments_data)

payments_df.to_csv(
    "payments.csv",
    index=False
)

print("payments.csv created successfully!")

payments.csv created successfully!

STEP 2 — Verify the CSV Files

In [ ]:
print(os.listdir())

['.config', 'products.csv', 'payments.csv', 'customers.csv', 'orders.csv', 'sample_data']

STEP 3 — Extract Data Using Pandas

In [ ]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
payments = pd.read_csv("payments.csv")

In [ ]:
print("CUSTOMERS")
display(customers)

print("PRODUCTS")
display(products)

print("ORDERS")
display(orders)

print("PAYMENTS")
display(payments)

CUSTOMERS

   Customer_ID   Name    City
0            1  Rahul  Mumbai
1            2  Sneha    Pune
2            3   Amit  Nashik
3            4  Priya  Mumbai
4            5   Neha   Thane

PRODUCTS

   Product_ID   Product     Category  Price
0         101    Laptop  Electronics  50000
1         102     Mouse  Electronics   2000
2         103     Chair    Furniture   8000
3         104    Mobile  Electronics  30000
4         105  Keyboard  Electronics   3000

ORDERS

   Order_ID  Customer_ID  Product_ID  Quantity
0      1001            1         101         1
1      1002            2         102         3
2      1003            3         103         2
3      1004            4         104         1
4      1005            5         105         2

PAYMENTS

   Payment_ID  Order_ID  Amount   Status
0         501      1001   50000     Paid
1         502      1002    6000     Paid
2         503      1003   16000     Paid
3         504      1004   30000  Pending
4         505      1005    6000     Paid

STEP 4 — Check the Data

In [ ]:
print("Customers missing values:")
print(customers.isnull().sum())

print("\nProducts missing values:")
print(products.isnull().sum())

print("\nOrders missing values:")
print(orders.isnull().sum())

print("\nPayments missing values:")
print(payments.isnull().sum())

Customers missing values:
Customer_ID    0
Name           0
City           0
dtype: int64

Products missing values:
Product_ID    0
Product       0
Category      0
Price         0
dtype: int64

Orders missing values:
Order_ID       0
Customer_ID    0
Product_ID     0
Quantity       0
dtype: int64

Payments missing values:
Payment_ID    0
Order_ID      0
Amount        0
Status        0
dtype: int64

STEP 5 — Check Duplicate Records

In [ ]:
print("Customer duplicates:", customers.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())
print("Order duplicates:", orders.duplicated().sum())
print("Payment duplicates:", payments.duplicated().sum())

Customer duplicates: 0
Product duplicates: 0
Order duplicates: 0
Payment duplicates: 0

STEP 6 — Clean the Data

In [ ]:
customers = customers.drop_duplicates()
products = products.drop_duplicates()
orders = orders.drop_duplicates()
payments = payments.drop_duplicates()

In [ ]:
customers["Name"] = customers["Name"].str.strip().str.upper()

In [ ]:
customers["City"] = customers["City"].str.strip().str.upper()

In [ ]:
products["Product"] = products["Product"].str.strip().str.upper()

In [ ]:
products["Category"] = products["Category"].str.strip().str.upper()

STEP 7 — Transform the Orders Data

In [ ]:
order_details = orders.merge(
    products,
    on="Product_ID",
    how="left"
)

In [ ]:
order_details["Total_Amount"] = (
    order_details["Price"] *
    order_details["Quantity"]
)

In [ ]:
display(order_details)

,Order_ID,Customer_ID,Product_ID,Quantity,Product,Category,Price,Total_Amount
0,1001,1,101,1,LAPTOP,ELECTRONICS,50000,50000
1,1002,2,102,3,MOUSE,ELECTRONICS,2000,6000
2,1003,3,103,2,CHAIR,FURNITURE,8000,16000
3,1004,4,104,1,MOBILE,ELECTRONICS,30000,30000
4,1005,5,105,2,KEYBOARD,ELECTRONICS,3000,6000

STEP 8 — Validate the Data

In [ ]:
assert customers["Customer_ID"].notnull().all()
assert products["Product_ID"].notnull().all()
assert orders["Order_ID"].notnull().all()
assert payments["Payment_ID"].notnull().all()

assert (products["Price"] > 0).all()
assert (orders["Quantity"] > 0).all()
assert (payments["Amount"] >= 0).all()

print("Data validation successful!")

Data validation successful!

# STEP 9 — Create SQL Database and Load Data

Step 9.1 — Create the SQL Database

In [ ]:
import sqlite3

connection = sqlite3.connect("ecommerce.db")

print("SQL database created successfully!")

SQL database created successfully!

Step 9.2 — Load Customers into SQL

In [ ]:
customers.to_sql(
    "customers",
    connection,
    if_exists="replace",
    index=False
)

print("Customers table loaded successfully!")

Customers table loaded successfully!

Step 9.3 — Load Products

In [ ]:
products.to_sql(
    "products",
    connection,
    if_exists="replace",
    index=False
)

print("Products table loaded successfully!")

Products table loaded successfully!

Step 9.4 — Load Orders

In [ ]:
orders.to_sql(
    "orders",
    connection,
    if_exists="replace",
    index=False
)

print("Orders table loaded successfully!")

Orders table loaded successfully!

Step 9.5 — Load Payments

In [ ]:
payments.to_sql(
    "payments",
    connection,
    if_exists="replace",
    index=False
)

print("Payments table loaded successfully!")

Payments table loaded successfully!

Step 9.6 — Check Tables in Database

In [ ]:
tables = pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    connection
)

display(tables)

        name
0  customers
1   products
2     orders
3   payments

STEP 9.7 — Read Customers from SQL

In [ ]:
result = pd.read_sql(
    "SELECT * FROM customers",
    connection
)

display(result)

   Customer_ID   Name    City
0            1  RAHUL  MUMBAI
1            2  SNEHA    PUNE
2            3   AMIT  NASHIK
3            4  PRIYA  MUMBAI
4            5   NEHA   THANE

STEP 9.8 — Read Products from SQL

In [ ]:
result = pd.read_sql(
    "SELECT * FROM products",
    connection
)

display(result)

   Product_ID   Product     Category  Price
0         101    LAPTOP  ELECTRONICS  50000
1         102     MOUSE  ELECTRONICS   2000
2         103     CHAIR    FURNITURE   8000
3         104    MOBILE  ELECTRONICS  30000
4         105  KEYBOARD  ELECTRONICS   3000

STEP 9.9 — Read Orders from SQL

In [ ]:
result = pd.read_sql(
    "SELECT * FROM orders",
    connection
)

display(result)

   Order_ID  Customer_ID  Product_ID  Quantity
0      1001            1         101         1
1      1002            2         102         3
2      1003            3         103         2
3      1004            4         104         1
4      1005            5         105         2

STEP 9.10 — Read Payments from SQL

In [ ]:
result = pd.read_sql(
    "SELECT * FROM payments",
    connection
)

display(result)

   Payment_ID  Order_ID  Amount   Status
0         501      1001   50000     Paid
1         502      1002    6000     Paid
2         503      1003   16000     Paid
3         504      1004   30000  Pending
4         505      1005    6000     Paid

STEP 9.11 — Perform a SQL Join

In [ ]:
report = pd.read_sql(
    """
    SELECT
        o.Order_ID,
        c.Name AS Customer_Name,
        c.City,
        p.Product,
        p.Category,
        o.Quantity,
        p.Price,
        (o.Quantity * p.Price) AS Total_Amount,
        pay.Status AS Payment_Status
    FROM orders o
    JOIN customers c
        ON o.Customer_ID = c.Customer_ID
    JOIN products p
        ON o.Product_ID = p.Product_ID
    JOIN payments pay
        ON o.Order_ID = pay.Order_ID
    """,
    connection
)

display(report)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Total_Amount,Payment_Status
0,1001,RAHUL,MUMBAI,LAPTOP,ELECTRONICS,1,50000,50000,Paid
1,1002,SNEHA,PUNE,MOUSE,ELECTRONICS,3,2000,6000,Paid
2,1003,AMIT,NASHIK,CHAIR,FURNITURE,2,8000,16000,Paid
3,1004,PRIYA,MUMBAI,MOBILE,ELECTRONICS,1,30000,30000,Pending
4,1005,NEHA,THANE,KEYBOARD,ELECTRONICS,2,3000,6000,Paid

STEP 9.12 — Calculate Total Revenue

In [ ]:
total_revenue = pd.read_sql(
    """
    SELECT SUM(o.Quantity * p.Price) AS Total_Revenue
    FROM orders o
    JOIN products p
        ON o.Product_ID = p.Product_ID
    """,
    connection
)

display(total_revenue)

   Total_Revenue
0         108000

STEP 9.13 — Calculate Sales by Category

In [ ]:
category_report = pd.read_sql(
    """
    SELECT
        p.Category,
        SUM(o.Quantity * p.Price) AS Total_Sales
    FROM orders o
    JOIN products p
        ON o.Product_ID = p.Product_ID
    GROUP BY p.Category
    """,
    connection
)

display(category_report)

      Category  Total_Sales
0  ELECTRONICS        92000
1    FURNITURE        16000

STEP 9.14 — Save the Report as CSV

In [ ]:
report.to_csv(
    "ecommerce_report.csv",
    index=False
)

print("E-commerce report generated successfully!")

E-commerce report generated successfully!

STEP 9.15 — Close the Database

In [ ]:
connection.close()

print("Database connection closed.")

Database connection closed.

# STEP 10 — Handle Historical and Newly Arriving Data

STEP 10.1 — Create New Orders

In [ ]:
new_orders_data = {
    "Order_ID": [1006, 1007],
    "Customer_ID": [1, 3],
    "Product_ID": [102, 101],
    "Quantity": [2, 1]
}

new_orders_df = pd.DataFrame(new_orders_data)

new_orders_df.to_csv(
    "new_orders.csv",
    index=False
)

print("New orders file created successfully!")

New orders file created successfully!

STEP 10.2 — Read the Newly Arriving Data

In [ ]:
new_orders = pd.read_csv("new_orders.csv")

print("Newly arriving orders:")
display(new_orders)

Newly arriving orders:

   Order_ID  Customer_ID  Product_ID  Quantity
0      1006            1         102         2
1      1007            3         101         1

STEP 10.3 — Connect to the Existing Database

In [ ]:
connection = sqlite3.connect("ecommerce.db")

print("Connected to existing database!")

Connected to existing database!

STEP 10.4 — Read Historical Order IDs

In [ ]:
historical_orders = pd.read_sql(
    "SELECT Order_ID FROM orders",
    connection
)

print("Historical Order IDs:")
display(historical_orders)

Historical Order IDs:

   Order_ID
0      1001
1      1002
2      1003
3      1004
4      1005

STEP 10.5 — Identify Only New Orders

In [ ]:
new_records = new_orders[
    ~new_orders["Order_ID"].isin(
        historical_orders["Order_ID"]
    )
].copy()

print("New records identified:")
display(new_records)

New records identified:

   Order_ID  Customer_ID  Product_ID  Quantity
0      1006            1         102         2
1      1007            3         101         1

STEP 10.6 — Validate New Orders

In [ ]:
assert new_records["Order_ID"].notnull().all()
assert new_records["Customer_ID"].notnull().all()
assert new_records["Product_ID"].notnull().all()
assert (new_records["Quantity"] > 0).all()

print("New order validation successful!")

New order validation successful!

STEP 10.7 — Load Only New Records

In [ ]:
if not new_records.empty:

    new_records.to_sql(
        "orders",
        connection,
        if_exists="append",
        index=False
    )

    print(
        len(new_records),
        "new orders loaded successfully!"
    )

else:

    print("No new orders found.")

2 new orders loaded successfully!

STEP 10.8 — Verify the Database

In [ ]:
all_orders = pd.read_sql(
    "SELECT * FROM orders",
    connection
)

display(all_orders)

   Order_ID  Customer_ID  Product_ID  Quantity
0      1001            1         101         1
1      1002            2         102         3
2      1003            3         103         2
3      1004            4         104         1
4      1005            5         105         2
5      1006            1         102         2
6      1007            3         101         1

STEP 10.9 — Check That Duplicate Loading Doesn't Happen

In [ ]:
historical_orders = pd.read_sql(
    "SELECT Order_ID FROM orders",
    connection
)

new_records = new_orders[
    ~new_orders["Order_ID"].isin(
        historical_orders["Order_ID"]
    )
].copy()

print("New records found:", len(new_records))

New records found: 0

STEP 10.10 — Close the Database

In [ ]:
connection.close()

print("Database connection closed.")

Database connection closed.

In [1]:
import pandas as pd
import sqlite3
import os

# Create sample e-commerce CSV files
customers_data = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4, 5],
    "CustomerName": ["Customer A", "Customer B", "Customer C", "Customer D", "Customer E"],
    "Email": ["a@gmail.com", "b@gmail.com", "c@gmail.com", "d@gmail.com", "e@gmail.com"],
    "City": ["Mumbai", "Pune", "Nashik", "Thane", "Kalyan"]
})

products_data = pd.DataFrame({
    "ProductID": [101, 102, 103, 104, 105],
    "ProductName": ["Laptop", "Mobile", "Headphones", "Shoes", "Bag"],
    "Category": ["Electronics", "Electronics", "Electronics", "Fashion", "Fashion"],
    "Price": [55000, 25000, 2000, 3000, 2200]
})

orders_data = pd.DataFrame({
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "CustomerID": [1, 2, 3, 4, 5],
    "ProductID": [101, 102, 103, 104, 105],
    "Quantity": [1, 2, 3, 1, 2],
    "OrderDate": ["2026-01-10", "2026-02-15", "2026-03-20", "2026-04-12", "2026-05-18"]
})

payments_data = pd.DataFrame({
    "PaymentID": [501, 502, 503, 504, 505],
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "PaymentMethod": ["UPI", "Card", "Cash", "UPI", "Card"],
    "PaymentStatus": ["Paid", "Paid", "Paid", "Paid", "Pending"]
})

customers_data.to_csv("customers.csv", index=False)
products_data.to_csv("products.csv", index=False)
orders_data.to_csv("orders.csv", index=False)
payments_data.to_csv("payments.csv", index=False)

# Extract CSV data
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
payments = pd.read_csv("payments.csv")

# Data cleaning
customers = customers.drop_duplicates()
products = products.drop_duplicates()
orders = orders.drop_duplicates()
payments = payments.drop_duplicates()

customers["CustomerName"] = customers["CustomerName"].str.strip()
customers["Email"] = customers["Email"].str.strip().str.lower()

products["ProductName"] = products["ProductName"].str.strip()
products["Price"] = pd.to_numeric(products["Price"], errors="coerce")

orders["Quantity"] = pd.to_numeric(orders["Quantity"], errors="coerce")
orders["OrderDate"] = pd.to_datetime(orders["OrderDate"], errors="coerce")

payments["PaymentMethod"] = payments["PaymentMethod"].str.strip()
payments["PaymentStatus"] = payments["PaymentStatus"].str.strip()

# Remove invalid records
customers = customers.dropna()
products = products.dropna()
orders = orders.dropna()
payments = payments.dropna()

orders = orders[orders["Quantity"] > 0]
products = products[products["Price"] > 0]

# Create SQL database
conn = sqlite3.connect("ecommerce.db")

# Historical data loading
customers.to_sql("customers", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
orders.to_sql("orders", conn, if_exists="replace", index=False)
payments.to_sql("payments", conn, if_exists="replace", index=False)

# Newly arriving data
new_orders = pd.DataFrame({
    "OrderID": [1006, 1007],
    "CustomerID": [1, 3],
    "ProductID": [102, 101],
    "Quantity": [1, 1],
    "OrderDate": ["2026-06-10", "2026-06-15"]
})

new_orders["OrderDate"] = pd.to_datetime(new_orders["OrderDate"])
new_orders["Quantity"] = pd.to_numeric(new_orders["Quantity"])

existing_orders = pd.read_sql("SELECT OrderID FROM orders", conn)

new_orders = new_orders[
    ~new_orders["OrderID"].isin(existing_orders["OrderID"])
]

new_orders.to_sql("orders", conn, if_exists="append", index=False)

# Generate report
report = pd.read_sql("""
SELECT
    o.OrderID,
    c.CustomerName,
    p.ProductName,
    p.Category,
    p.Price,
    o.Quantity,
    (p.Price * o.Quantity) AS TotalAmount,
    o.OrderDate,
    pay.PaymentMethod,
    pay.PaymentStatus
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON o.ProductID = p.ProductID
LEFT JOIN payments pay ON o.OrderID = pay.OrderID
ORDER BY o.OrderDate
""", conn)

print("E-COMMERCE SALES REPORT")
print(report)

print("\nSUMMARY REPORT")
print("Total Customers:", len(customers))
print("Total Products:", len(products))
print("Total Orders:", len(report))
print("Total Sales:", report["TotalAmount"].sum())

print("\nSales by Category:")
print(
    report.groupby("Category")["TotalAmount"]
    .sum()
    .reset_index()
    .rename(columns={"TotalAmount": "TotalSales"})
)

print("\nPayment Status:")
print(report["PaymentStatus"].value_counts())

conn.close()

print("\nETL Pipeline Completed Successfully!")

E-COMMERCE SALES REPORT
   OrderID CustomerName ProductName     Category  Price  Quantity  \
0     1001   Customer A      Laptop  Electronics  55000         1
1     1002   Customer B      Mobile  Electronics  25000         2
2     1003   Customer C  Headphones  Electronics   2000         3
3     1004   Customer D       Shoes      Fashion   3000         1
4     1005   Customer E         Bag      Fashion   2200         2
5     1006   Customer A      Mobile  Electronics  25000         1
6     1007   Customer C      Laptop  Electronics  55000         1

   TotalAmount            OrderDate PaymentMethod PaymentStatus
0        55000  2026-01-10 00:00:00           UPI          Paid
1        50000  2026-02-15 00:00:00          Card          Paid
2         6000  2026-03-20 00:00:00          Cash          Paid
3         3000  2026-04-12 00:00:00           UPI          Paid
4         4400  2026-05-18 00:00:00          Card       Pending
5        25000  2026-06-10 00:00:00          None          None
6        55000  2026-06-15 00:00:00          None          None

SUMMARY REPORT
Total Customers: 5
Total Products: 5
Total Orders: 7
Total Sales: 198400

Sales by Category:
      Category  TotalSales
0  Electronics      191000
1      Fashion        7400

Payment Status:
PaymentStatus
Paid       4
Pending    1
Name: count, dtype: int64

ETL Pipeline Completed Successfully!