## **Practical No. 1 — Data Parsing, File Handling, Regular Expressions and SQL CRUD**

## **Exercise 1 :**

In [ ]:
import pandas as pd
import re
import json
import csv
import sqlite3
import os
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup

print("All required libraries imported successfully!")

All required libraries imported successfully!

STEP 1 — Create a Text File

In [ ]:
text_data = """Name: Rahul
Age: 21
City: Mumbai
Course: Data Science
"""

with open("student.txt", "w") as file:
    file.write(text_data)

print("Text file created successfully!")

Text file created successfully!

STEP 2 — Read and Parse the Text File

In [ ]:
with open("student.txt", "r") as file:
    text = file.read()

print(text)

Name: Rahul
Age: 21
City: Mumbai
Course: Data Science

STEP 3 — Extract Data from Text File

In [ ]:
student_data = {}

for line in text.splitlines():
    key, value = line.split(":", 1)
    student_data[key.strip()] = value.strip()

print(student_data)

{'Name': 'Rahul', 'Age': '21', 'City': 'Mumbai', 'Course': 'Data Science'}

STEP 4 — Create a CSV File

In [ ]:
students = [
    [1, "Rahul", 21, "Mumbai", "Data Science"],
    [2, "Sneha", 20, "Pune", "Computer Science"],
    [3, "Amit", None, "Nashik", "Data Science"],
    [4, "Priya", 22, None, "AI"]
]

with open("students.csv", "w", newline="") as file:
    writer = csv.writer(file)

    writer.writerow([
        "Student_ID",
        "Name",
        "Age",
        "City",
        "Course"
    ])

    writer.writerows(students)

print("CSV file created successfully!")

CSV file created successfully!

STEP 5 — Read the CSV File

In [ ]:
df = pd.read_csv("students.csv")

display(df)

   Student_ID   Name   Age    City            Course
0           1  Rahul  21.0  Mumbai      Data Science
1           2  Sneha  20.0    Pune  Computer Science
2           3   Amit   NaN  Nashik      Data Science
3           4  Priya  22.0     NaN                AI

STEP 6 — Check Missing Values

In [ ]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
Student_ID    0
Name          0
Age           1
City          1
Course        0
dtype: int64

STEP 7 — Check Anomalies

In [ ]:
invalid_age = df[
    (df["Age"].notnull()) &
    (df["Age"] <= 0)
]

print("Invalid age records:")
display(invalid_age)

Invalid age records:

Empty DataFrame
Columns: [Student_ID, Name, Age, City, Course]
Index: []

In [ ]:
duplicate_ids = df[
    df["Student_ID"].duplicated()
]

print("Duplicate Student IDs:")
display(duplicate_ids)

Duplicate Student IDs:

Empty DataFrame
Columns: [Student_ID, Name, Age, City, Course]
Index: []

STEP 8 — Create an HTML File

In [ ]:
html_data = """
<html>
<body>
<h1>Student Information</h1>

<table>
<tr>
<th>ID</th>
<th>Name</th>
<th>Course</th>
</tr>

<tr>
<td>1</td>
<td>Rahul</td>
<td>Data Science</td>
</tr>

<tr>
<td>2</td>
<td>Sneha</td>
<td>Computer Science</td>
</tr>
</table>

</body>
</html>
"""

with open("students.html", "w") as file:
    file.write(html_data)

print("HTML file created successfully!")

HTML file created successfully!

STEP 9 — Parse HTML

In [ ]:
with open("students.html", "r") as file:
    html = file.read()

soup = BeautifulSoup(html, "html.parser")

table = soup.find("table")

rows = []

for row in table.find_all("tr"):
    cells = row.find_all(["th", "td"])
    rows.append([
        cell.get_text(strip=True)
        for cell in cells
    ])

for row in rows:
    print(row)

['ID', 'Name', 'Course']
['1', 'Rahul', 'Data Science']
['2', 'Sneha', 'Computer Science']

STEP 10 — Create an XML File

In [ ]:
xml_data = """
<students>
    <student>
        <id>1</id>
        <name>Rahul</name>
        <course>Data Science</course>
    </student>

    <student>
        <id>2</id>
        <name>Sneha</name>
        <course>Computer Science</course>
    </student>
</students>
"""

with open("students.xml", "w") as file:
    file.write(xml_data)

print("XML file created successfully!")

XML file created successfully!

STEP 11 — Parse XML

In [ ]:
tree = ET.parse("students.xml")
root = tree.getroot()

for student in root.findall("student"):
    student_id = student.find("id").text
    name = student.find("name").text
    course = student.find("course").text

    print(
        "ID:", student_id,
        "| Name:", name,
        "| Course:", course
    )

ID: 1 | Name: Rahul | Course: Data Science
ID: 2 | Name: Sneha | Course: Computer Science

STEP 12 — Create a JSON File

In [ ]:
json_data = {
    "students": [
        {
            "id": 1,
            "name": "Rahul",
            "course": "Data Science"
        },
        {
            "id": 2,
            "name": "Sneha",
            "course": "Computer Science"
        }
    ]
}

with open("students.json", "w") as file:
    json.dump(json_data, file, indent=4)

print("JSON file created successfully!")

JSON file created successfully!

STEP 13 — Parse JSON

In [ ]:
with open("students.json", "r") as file:
    data = json.load(file)

for student in data["students"]:
    print(
        "ID:", student["id"],
        "| Name:", student["name"],
        "| Course:", student["course"]
    )

ID: 1 | Name: Rahul | Course: Data Science
ID: 2 | Name: Sneha | Course: Computer Science

## **Exercise 2 — Read and Write Binary Files**

STEP 14 — Write Data to a Binary File

In [ ]:
import pickle

print("Pickle imported successfully!")

Pickle imported successfully!

STEP 15 — Create Data

In [ ]:
student = {
    "Student_ID": 101,
    "Name": "Rahul",
    "Age": 21,
    "Course": "Data Science"
}

print(student)

{'Student_ID': 101, 'Name': 'Rahul', 'Age': 21, 'Course': 'Data Science'}

STEP 16 — Write the Data to a Binary File

In [ ]:
with open("student.dat", "wb") as file:
    pickle.dump(student, file)

print("Data written to binary file successfully!")

Data written to binary file successfully!

STEP 17 — Read the Binary File

In [ ]:
with open("student.dat", "rb") as file:
    loaded_student = pickle.load(file)

print("Data read from binary file:")
print(loaded_student)

Data read from binary file:
{'Student_ID': 101, 'Name': 'Rahul', 'Age': 21, 'Course': 'Data Science'}

STEP 18 — Write Multiple Records

In [ ]:
students = [
    {
        "Student_ID": 101,
        "Name": "Rahul",
        "Age": 21,
        "Course": "Data Science"
    },
    {
        "Student_ID": 102,
        "Name": "Sneha",
        "Age": 20,
        "Course": "Computer Science"
    },
    {
        "Student_ID": 103,
        "Name": "Amit",
        "Age": 22,
        "Course": "Artificial Intelligence"
    }
]

with open("students.dat", "wb") as file:
    pickle.dump(students, file)

print("Multiple student records written successfully!")

Multiple student records written successfully!

STEP 19 — Read Multiple Records

In [ ]:
with open("students.dat", "rb") as file:
    loaded_students = pickle.load(file)

print("Students from binary file:")

for student in loaded_students:
    print(student)

Students from binary file:
{'Student_ID': 101, 'Name': 'Rahul', 'Age': 21, 'Course': 'Data Science'}
{'Student_ID': 102, 'Name': 'Sneha', 'Age': 20, 'Course': 'Computer Science'}
{'Student_ID': 103, 'Name': 'Amit', 'Age': 22, 'Course': 'Artificial Intelligence'}

STEP 20 — Verify the Binary File Exists

In [ ]:
import os

print("student.dat exists:", os.path.exists("student.dat"))
print("students.dat exists:", os.path.exists("students.dat"))

student.dat exists: True
students.dat exists: True

## **Exercise 3: Searching, Splitting and Replacing Strings using Regular Expressions**

STEP 21 — Import the re Module

In [ ]:
import re

print("Regular expression module imported successfully!")

Regular expression module imported successfully!

STEP 22 — Searching Using Regular Expression

In [ ]:
text = "My email is rahul@gmail.com and my phone number is 9876543210."

print(text)

My email is rahul@gmail.com and my phone number is 9876543210.

In [ ]:
pattern = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"

result = re.search(pattern, text)

if result:
    print("Email found:", result.group())
else:
    print("Email not found")

Email found: rahul@gmail.com

STEP 23 — Search for a Phone Number

In [ ]:
phone_pattern = r"\b\d{10}\b"

phone = re.search(phone_pattern, text)

if phone:
    print("Phone number found:", phone.group())
else:
    print("Phone number not found")

Phone number found: 9876543210

STEP 24 — Find All Matching Values

In [ ]:
text = """
Contact rahul@gmail.com
or sneha@gmail.com
or amit@yahoo.com
"""

emails = re.findall(
    r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
    text
)

print("Emails found:")
print(emails)

Emails found:
['rahul@gmail.com', 'sneha@gmail.com', 'amit@yahoo.com']

STEP 25 — Splitting Strings Using Regex

In [ ]:
text = "Apple,Orange;Banana Mango|Grapes"

print(text)

Apple,Orange;Banana Mango|Grapes

In [ ]:
parts = re.split(
    r"[,; |]+",
    text
)

print(parts)

['Apple', 'Orange', 'Banana', 'Mango', 'Grapes']

STEP 26 — Another Splitting Example

In [ ]:
sentence = "Python is easy to learn"

words = re.split(
    r"\s+",
    sentence
)

print(words)

['Python', 'is', 'easy', 'to', 'learn']

STEP 27 — Replacing Strings Using Regex

In [ ]:
text = "Contact Rahul at 9876543210."

new_text = re.sub(
    r"\b\d{10}\b",
    "XXXXXXXXXX",
    text
)

print(new_text)

Contact Rahul at XXXXXXXXXX.

STEP 28 — Replace Multiple Numbers

In [ ]:
text = "Rahul: 9876543210, Sneha: 9123456789"

new_text = re.sub(
    r"\b\d{10}\b",
    "XXXXXXXXXX",
    text
)

print(new_text)

Rahul: XXXXXXXXXX, Sneha: XXXXXXXXXX

STEP 29 — Replace Extra Spaces

In [ ]:
text = "Python     is    very      easy"

clean_text = re.sub(
    r"\s+",
    " ",
    text
)

print(clean_text)

Python is very easy

## **Exercise 4: SQL CRUD Operations**

In [ ]:
import sqlite3

print("SQLite imported successfully!")

SQLite imported successfully!

STEP 30 — Create the Database

In [ ]:
connection = sqlite3.connect("student_database.db")

print("Database created successfully!")

Database created successfully!

STEP 31 — Create a Student Table

In [ ]:
cursor = connection.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    Student_ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Age INTEGER,
    City TEXT,
    Course TEXT
)
""")

connection.commit()

print("Students table created successfully!")

Students table created successfully!

STEP 32 — CREATE: Insert Records

In [ ]:
students = [
    (1, "Rahul", 21, "Mumbai", "Data Science"),
    (2, "Sneha", 20, "Pune", "Computer Science"),
    (3, "Amit", 22, "Nashik", "Artificial Intelligence"),
    (4, "Priya", 21, "Thane", "Data Science")
]

cursor.executemany("""
INSERT INTO students
(Student_ID, Name, Age, City, Course)
VALUES (?, ?, ?, ?, ?)
""", students)

connection.commit()

print("Student records inserted successfully!")

Student records inserted successfully!

STEP 33 — READ: Display All Records

In [ ]:
cursor.execute("SELECT * FROM students")

records = cursor.fetchall()

for record in records:
    print(record)

(1, 'Rahul', 21, 'Mumbai', 'Data Science')
(2, 'Sneha', 20, 'Pune', 'Computer Science')
(3, 'Amit', 22, 'Nashik', 'Artificial Intelligence')
(4, 'Priya', 21, 'Thane', 'Data Science')

STEP 34 — READ: Select Specific Columns

In [ ]:
cursor.execute("""
SELECT Name, Course
FROM students
""")

records = cursor.fetchall()

for record in records:
    print(record)

('Rahul', 'Data Science')
('Sneha', 'Computer Science')
('Amit', 'Artificial Intelligence')
('Priya', 'Data Science')

STEP 35 — READ: Search for a Student

In [ ]:
cursor.execute("""
SELECT *
FROM students
WHERE Course = 'Data Science'
""")

records = cursor.fetchall()

for record in records:
    print(record)

(1, 'Rahul', 21, 'Mumbai', 'Data Science')
(4, 'Priya', 21, 'Thane', 'Data Science')

STEP 36 — UPDATE: Modify a Record

In [ ]:
cursor.execute("""
UPDATE students
SET City = 'Pune'
WHERE Student_ID = 1
""")

connection.commit()

print("Student record updated successfully!")

Student record updated successfully!

STEP 37— Verify the UPDATE

In [ ]:
cursor.execute("""
SELECT *
FROM students
WHERE Student_ID = 1
""")

print(cursor.fetchone())

(1, 'Rahul', 21, 'Pune', 'Data Science')

STEP 38 — DELETE: Remove a Record

In [ ]:
cursor.execute("""
DELETE FROM students
WHERE Student_ID = 4
""")

connection.commit()

print("Student record deleted successfully!")

Student record deleted successfully!

STEP 39 — Verify DELETE

In [ ]:
cursor.execute("SELECT * FROM students")

records = cursor.fetchall()

for record in records:
    print(record)

(1, 'Rahul', 21, 'Pune', 'Data Science')
(2, 'Sneha', 20, 'Pune', 'Computer Science')
(3, 'Amit', 22, 'Nashik', 'Artificial Intelligence')

STEP 40 — Check Number of Records

In [ ]:
cursor.execute("SELECT COUNT(*) FROM students")

count = cursor.fetchone()[0]

print("Total students:", count)

Total students: 3

STEP 41 — Close the Database

In [ ]:
connection.close()

print("Database connection closed.")

Database connection closed.

In [ ]:
print("Mayuri Narsu Patil")

Mayuri Narsu Patil